name: test
on: [push, pull_request]

jobs:
  linux:
    name: ${{ matrix.os }}-${{ matrix.dc }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        dc: [ dmd-latest ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}
      - name: Run tests
        run: |
          dub test --coverage
      - name: 'Upload coverage to Codecov'
        if: matrix.dc == 'dmd-latest'
        uses: codecov/codecov-action@v1
